version: "3.9"

services:
  ledger:
    depends_on:
      database:
        condition: service_healthy
      ollama:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
      target: ledger
    env_file:
      - .env
    volumes:
      - ./apps/backend/:/app/backend/:rw
      - ./apps/auth/:/app/auth/:rw
      - ./shared/:/app/shared:rw
    expose:
      - ${APP_PORT}
    networks:
      - local
    command:
      - "backend.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8082"
      - "--reload"

  auth:
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
      target: ledger
    env_file:
      - .env
    volumes:
      - ./apps/auth/:/app/auth/:rw
      - ./shared/:/app/shared:rw
    expose:
      - "8081"
    command:
      - auth.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8081"
      - --reload
    networks:
      - local

  front:
    build:
      context: .
      dockerfile: Dockerfile
      target: reactapp
    volumes:
      - ./apps/frontend/:/app:cached
      - /app/node_modules
    environment:
      NODE_ENV: development
      VITE_ESBUILD_VERSION: 0.25.10
    command: npm run dev -- --host 0.0.0.0
    expose:
      - "5173"
    networks:
      - local

  database:
    build:
      context: .
      dockerfile: Dockerfile
      target: database
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "1"
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - ./config/database/dev-ver/:/docker-entrypoint-initdb.d:ro
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - local

  dbadmin:
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
      target: dbadmin
    expose:
      - "8080"
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - local

  reverseproxy:
    depends_on:
      auth:
        condition: service_started
      ledger:
        condition: service_started
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
      target: reverseproxy
    env_file:
      - .env
    environment:
      NODE_ENV: development
    restart: unless-stopped
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx/mime.types:/etc/nginx/mime.types:ro
    networks:
      - local
    ports:
      - "${APP_PORT}:80"

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    environment:
      - LISTEN_ADDRESS=0.0.0.0
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - local

volumes:
  ollama:

networks:
  local:
    driver: bridge
